In [1]:
import numpy as np

In [3]:
integer_array = np.arange(12)

In [7]:
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
integer_array[3]

3

In [11]:
integer_array[-2]

10

In [13]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [15]:
integer_array[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
integer_array[:-3]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [21]:
new_array = integer_array.reshape(3,4)

In [23]:
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
new_array[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
new_array[1,:]

array([4, 5, 6, 7])

In [29]:
new_array[1,:]

array([4, 5, 6, 7])

In [31]:
new_array[1:,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
new_array[1,2]

6

In [39]:
new_array[:,0]

array([0, 4, 8])

In [45]:
rng = np.random.default_rng(616)

inventory = rng.integers(0,100,10)

inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [47]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33], dtype=int64)

In [49]:
inventory /2


array([19.5, 19.5, 46.5, 43. , 24. , 23. , 24. , 15. ,  5.5, 28.5])

In [127]:
price = (rng.random(10) * 10).round(2)

price

array([3.36, 6.33, 6.29, 3.64, 6.47, 2.98, 5.94, 6.61, 2.78, 0.86])

In [131]:
(price * inventory)

array([131.04, 246.87, 584.97, 313.04, 310.56, 137.08, 285.12, 198.3 ,
        30.58,  49.02])

In [67]:
inventory_list = list(inventory)

inventory_list

[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]

In [73]:
filtering_array = np.arange(20)

filtering_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [75]:
filtering_array % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [77]:
filtering_array[filtering_array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [79]:
even_odd = np.array(['even','odd']*10)
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [81]:
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [87]:
filtering_array[even_odd != 'odd'] = 0

filtering_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [91]:
filtering_array[2] = 2

filtering_array

array([ 0,  1,  2,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [103]:
mask = (even_odd != 'odd') | (even_odd != 'even')
even_odd[mask]

array(['odd', 'odd', 'odd', 'odd', 'odd', 'odd', 'odd', 'odd', 'odd',
       'odd'], dtype='<U4')

In [107]:
np.where(filtering_array % 2 == 0,'even','odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [109]:
np.where(filtering_array % 2 == 0,'even',np.where(filtering_array == 9,filtering_array,'odd'))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U11')

In [135]:
inventory.mean()

49.7

In [147]:
price.max()

6.61

In [157]:
(price * inventory).argmin()

8

In [163]:
price_2d = price.reshape(5,2)
price_2d

array([[3.36, 6.33],
       [6.29, 3.64],
       [6.47, 2.98],
       [5.94, 6.61],
       [2.78, 0.86]])

In [171]:
price_2d.mean(axis=0)

array([4.968, 4.084])

In [179]:
inventory2 = np.array([79,22,20,48,8,76,12,16,5,64])
price2 = np.array([2.6,7.2,6.92,3.88,0.78,2.67,8.87,0.23,5.23,6.3])

product_value = price2 * inventory2
product_value.sort()
product_value

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [181]:
reshaped_product_value = product_value.reshape(2,5)
reshaped_product_value

array([[  3.68,   6.24,  26.15, 106.44, 138.4 ],
       [158.4 , 186.24, 202.92, 205.4 , 403.2 ]])

In [183]:
np.median(reshaped_product_value)

148.4

In [209]:
np.percentile(reshaped_product_value,10)

5.984

In [211]:
np.sqrt(reshaped_product_value)

array([[ 1.91833261,  2.4979992 ,  5.11370707, 10.3169763 , 11.76435294],
       [12.58570618, 13.64697769, 14.24499912, 14.33178286, 20.07984064]])

In [215]:
np.unique(reshaped_product_value)

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])