In [1]:
import numpy as np

In [5]:
# Assignment 2
rng = np.random.default_rng(2022)

random_array = rng.random(9).reshape(3,3)

random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [11]:
# Assignment 3
random_array[:2]


array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [31]:
random_array[:,0]

array([0.24742606, 0.06066207, 0.1108689 ])

In [37]:
random_array[2,1]

0.04305584439252108

In [61]:
# Assignemnt 4

prices = np.array([5.99,6.99,22.49,99.99,4.99,49.99])

total = prices + 5

discount_pct = random_array[:2,:].reshape(6)

In [63]:
pct_owed = 1 - discount_pct

In [67]:
final_owed = pct_owed * total

In [69]:
final_owed.round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

In [89]:
# Assignment 5

products = np.array(['salad','bread','mustard','rare tomato','cola','gourmet ice cream'])

products[prices > 25]

array(['rare tomato', 'gourmet ice cream'], dtype='<U17')

In [109]:
mask = (prices > 25) | (products == 'cola')
fancy_feast_special = products[mask]
fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [107]:
new_shipping_cost = np.where(prices > 20,0,5)
new_shipping_cost

array([5, 5, 0, 0, 5, 0])

In [141]:
# Assignment 6

prices.sort()
top_three_prices = prices[-3:]
min_price = top_three_prices.min()
max_price = top_three_prices.max()
mean_price = top_three_prices.mean()
median_price = np.median(top_three_prices)
top_three_prices


array([22.49, 49.99, 99.99])

In [135]:
price_tiers = np.array(['budget','budget','mid-tier','luxury','mid-tier','luxury'])
np.unique(price_tiers).size

3

In [7]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv("retail/retail_2016_2017.csv",skiprows=range(1,11000),nrows=1000)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])

In [13]:
mask = (family_array == "PRODUCE")
masked_sales_array = sales_array[mask]
masked_sales_array

array([1662.394,  447.064, 2423.944,  962.866, 1236.404,  298.441,
       1077.44 , 3404.531,  962.96 ,  279.505, 1852.786, 1089.319,
        726.516, 7860.031,  446.038, 1155.385,  120.202,  862.092,
        473.952,  254.263, 1272.755, 2775.771, 2030.762, 1657.432,
       2339.906,  722.333, 1567.843, 2458.456,  673.885, 8834.15 ])

In [51]:
random_array = rng.random(30)
sampled_array = masked_sales_array[random_array < 0.5] 

In [33]:
mean = sampled_array.mean()
median = np.median(sampled_array)

In [53]:
np.where(sampled_array < median,"below_both",np.where(sampled_array > mean,"above_both","above_median"))

array(['below_both', 'above_median', 'below_both', 'below_both',
       'below_both', 'above_median', 'below_both', 'below_both',
       'above_median', 'above_both', 'above_both', 'below_both',
       'above_median', 'above_both', 'above_both'], dtype='<U12')